package ru.hse.lyubortk.trie;

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

/** Interface which indicates that class supports serialization */
public interface Serializable {
    /**
     * Write object state as byte sequence.
     * @param out non-null {@link OutputStream} to write object state to
     */
    void serialize(@NotNull OutputStream out) throws IOException;

    /**
     * Replace current object with one read from stream. The data
     * should be generated by {@link Serializable#serialize} method.
     * @param in non-null {@link InputStream} to read object state from
     */
    void deserialize(@NotNull InputStream in) throws IOException;
}
